// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StambenaZajednica.Data;

#nullable disable

namespace StambenaZajednica.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20250305184232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StambenaZajednica.Models.Finansije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDospeca")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumUplate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IznosDuga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IznosUplate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StambenaZajednicaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipTroska")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StambenaZajednicaId");

                    b.ToTable("Finansije");
                });

            modelBuilder.Entity("StambenaZajednica.Models.StambZajednica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojZgrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StambeneZajednice");
                });

            modelBuilder.Entity("StambenaZajednica.Models.Stan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojStana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaLiJeZakljucan")
                        .HasColumnType("bit");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StambenaZajednicaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StambenaZajednicaId");

                    b.ToTable("Stanovi");
                });

            modelBuilder.Entity("StambenaZajednica.Models.Finansije", b =>
                {
                    b.HasOne("StambenaZajednica.Models.StambZajednica", "StambenaZajednica")
                        .WithMany("Finansije")
                        .HasForeignKey("StambenaZajednicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StambenaZajednica");
                });

            modelBuilder.Entity("StambenaZajednica.Models.Stan", b =>
                {
                    b.HasOne("StambenaZajednica.Models.StambZajednica", "StambenaZajednica")
                        .WithMany("Stanovi")
                        .HasForeignKey("StambenaZajednicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StambenaZajednica");
                });

            modelBuilder.Entity("StambenaZajednica.Models.StambZajednica", b =>
                {
                    b.Navigation("Finansije");

                    b.Navigation("Stanovi");
                });
#pragma warning restore 612, 618
        }
    }
}
