// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StambenaZajednica.Data;

#nullable disable

namespace StambenaZajednica.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20250321163254_InitialMigrationRepositoryDbContext")]
    partial class InitialMigrationRepositoryDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StambenaZajednica.Models.Finansije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDospeca")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumUplate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IznosDuga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IznosUplate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StambenaZajednicaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipTroska")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StambenaZajednicaId");

                    b.ToTable("Finansije");
                });

            modelBuilder.Entity("StambenaZajednica.Models.StambZajednica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojZgrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StambeneZajednice");
                });

            modelBuilder.Entity("StambenaZajednica.Models.Stan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojStana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaLiJeZakljucan")
                        .HasColumnType("bit");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StambenaZajednicaId")
                        .HasColumnType("int");

                    b.Property<int?>("StanarId")
                        .HasColumnType("int");

                    b.Property<string>("StanarId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StambenaZajednicaId");

                    b.HasIndex("StanarId1");

                    b.ToTable("Stanovi");
                });

            modelBuilder.Entity("StambenaZajednica.Models.Stanar", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stanar");
                });

            modelBuilder.Entity("StambenaZajednica.Models.Finansije", b =>
                {
                    b.HasOne("StambenaZajednica.Models.StambZajednica", "StambenaZajednica")
                        .WithMany("Finansije")
                        .HasForeignKey("StambenaZajednicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StambenaZajednica");
                });

            modelBuilder.Entity("StambenaZajednica.Models.Stan", b =>
                {
                    b.HasOne("StambenaZajednica.Models.StambZajednica", "StambenaZajednica")
                        .WithMany("Stanovi")
                        .HasForeignKey("StambenaZajednicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StambenaZajednica.Models.Stanar", "Stanar")
                        .WithMany()
                        .HasForeignKey("StanarId1");

                    b.Navigation("StambenaZajednica");

                    b.Navigation("Stanar");
                });

            modelBuilder.Entity("StambenaZajednica.Models.StambZajednica", b =>
                {
                    b.Navigation("Finansije");

                    b.Navigation("Stanovi");
                });
#pragma warning restore 612, 618
        }
    }
}
